import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import {ReactNode} from "react";


const montserrat = Montserrat({
  subsets: ["latin","cyrillic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
